name: Deploy Backend to EC2 via S3 + CodeDeploy

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      AWS_REGION: ap-northeast-2
      S3_BUCKET: codedeploy-app-bucket-5634sang
      S3_KEY_PREFIX: backend

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Zip backend source code
        run: |
          zip -r backend.zip . -x "*.git*" -x "backend.zip"

      - name: Upload to S3
        run: |
          TIMESTAMP=$(date +%Y%m%dT%H%M)
          S3_KEY="${{ env.S3_KEY_PREFIX }}/backend-${TIMESTAMP}.zip"
          aws s3 cp backend.zip s3://${{ env.S3_BUCKET }}/$S3_KEY
          echo "S3_KEY=$S3_KEY" >> $GITHUB_ENV

      - name: Deploy via CodeDeploy
        run: |
          aws deploy create-deployment \
            --application-name backend-app \
            --deployment-group-name backend-deploy-group \
            --deployment-config-name CodeDeployDefault.AllAtOnce \
            --s3-location bucket=${{ env.S3_BUCKET }},bundleType=zip,key=$S3_KEY \
            --region ${{ env.AWS_REGION }}

